wandb_version: 1

use_wandb:
  desc: null
  value: true
use_cm:
  desc: null
  value: false
entity:
  desc: null
  value: connect-cv-13
project_name:
  desc: null
  value: Sementic-Segmentation-HJH
exp_name:
  desc: null
  value: my_test
exp_num:
  desc: null
  value: 0
user_name:
  desc: null
  value: my_name
datadir:
  desc: null
  value: ../input/data/
train_path:
  desc: null
  value: train/DCM/
label_path:
  desc: null
  value: train/outputs_json/
valid_file:
  desc: null
  value: valid.csv
test_file:
  desc: null
  value: test.csv
transform:
  desc: null
  value:
  - resize
seed:
  desc: null
  value: 223
model_name:
  desc: null
  value: SegModel
model_param:
  desc: null
  value:
    pretrained: true
    backbone: resnet18
classes:
  desc: null
  value:
  - finger-1
  - finger-2
  - finger-3
  - finger-4
  - finger-5
  - finger-6
  - finger-7
  - finger-8
  - finger-9
  - finger-10
  - finger-11
  - finger-12
  - finger-13
  - finger-14
  - finger-15
  - finger-16
  - finger-17
  - finger-18
  - finger-19
  - Trapezium
  - Trapezoid
  - Capitate
  - Hamate
  - Scaphoid
  - Lunate
  - Triquetrum
  - Pisiform
  - Radius
  - Ulna
num_classes:
  desc: null
  value: 29
batch_size:
  desc: null
  value: 8
opt_name:
  desc: null
  value: Adam
loss:
  desc: null
  value: bce_with_logit_loss
loss_param:
  desc: null
  value: {}
lr:
  desc: null
  value: 0.0001
lr_scheduler:
  desc: null
  value: StepLR
lr_scheduler_param:
  desc: null
  value:
    step_size: 3
weight_decay:
  desc: null
  value: 1.0e-06
epochs:
  desc: null
  value: 150
savedir:
  desc: null
  value: ./checkpoint
grad_accum_steps:
  desc: null
  value: 1
mixed_precision:
  desc: null
  value: fp16
patience:
  desc: null
  value: 100
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1686147398.637209
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 51
      - 53
      - 55
      - 63
      - 71
      - 80
      2:
      - 1
      - 5
      - 41
      - 49
      - 51
      - 53
      - 55
      - 63
      - 71
      - 80
      3:
      - 13
      - 16
      - 23
      4: 3.10.11
      5: 0.15.4
      8:
      - 5
